//go:build !ignore_autogenerated

// zz_generated.deepcopy.go 的手写等价实现（替代 controller-gen 生成）。
// SLO/SLOList 必须实现 runtime.Object（DeepCopyObject）与各字段的 DeepCopy，否则 scheme 注册失败。
package v1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

func (in *SLOSpec) DeepCopyInto(out *SLOSpec) {
	*out = *in
	if in.Labels != nil {
		out.Labels = make(map[string]string, len(in.Labels))
		for k, v := range in.Labels {
			out.Labels[k] = v
		}
	}
	if in.SLOs != nil {
		out.SLOs = make([]SLOItem, len(in.SLOs))
		for i := range in.SLOs {
			in.SLOs[i].DeepCopyInto(&out.SLOs[i])
		}
	}
}

func (in *SLOSpec) DeepCopy() *SLOSpec {
	if in == nil {
		return nil
	}
	out := new(SLOSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *SLOItem) DeepCopyInto(out *SLOItem) {
	*out = *in
	in.SLI.DeepCopyInto(&out.SLI)
	in.Alerting.DeepCopyInto(&out.Alerting)
}

func (in *SLOItem) DeepCopy() *SLOItem {
	if in == nil {
		return nil
	}
	out := new(SLOItem)
	in.DeepCopyInto(out)
	return out
}

func (in *SLISpec) DeepCopyInto(out *SLISpec) {
	*out = *in
	if in.Events != nil {
		out.Events = &EventsSLI{ErrorQuery: in.Events.ErrorQuery, TotalQuery: in.Events.TotalQuery}
	}
	if in.Raw != nil {
		out.Raw = &RawSLI{ErrorRatioQuery: in.Raw.ErrorRatioQuery}
	}
}

func (in *SLISpec) DeepCopy() *SLISpec {
	if in == nil {
		return nil
	}
	out := new(SLISpec)
	in.DeepCopyInto(out)
	return out
}

func (in *EventsSLI) DeepCopy() *EventsSLI {
	if in == nil {
		return nil
	}
	out := new(EventsSLI)
	*out = *in
	return out
}

func (in *RawSLI) DeepCopy() *RawSLI {
	if in == nil {
		return nil
	}
	out := new(RawSLI)
	*out = *in
	return out
}

func (in *AlertingSpec) DeepCopyInto(out *AlertingSpec) {
	*out = *in
	if in.Labels != nil {
		out.Labels = make(map[string]string, len(in.Labels))
		for k, v := range in.Labels {
			out.Labels[k] = v
		}
	}
	if in.PageAlert != nil {
		out.PageAlert = in.PageAlert.DeepCopy()
	}
	if in.TicketAlert != nil {
		out.TicketAlert = in.TicketAlert.DeepCopy()
	}
}

func (in *AlertingSpec) DeepCopy() *AlertingSpec {
	if in == nil {
		return nil
	}
	out := new(AlertingSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *AlertTier) DeepCopyInto(out *AlertTier) {
	*out = *in
	if in.Labels != nil {
		out.Labels = make(map[string]string, len(in.Labels))
		for k, v := range in.Labels {
			out.Labels[k] = v
		}
	}
	if in.BurnThreshold != nil {
		out.BurnThreshold = new(float64)
		*out.BurnThreshold = *in.BurnThreshold
	}
	if in.Windows != nil {
		out.Windows = make([]string, len(in.Windows))
		copy(out.Windows, in.Windows)
	}
}

func (in *AlertTier) DeepCopy() *AlertTier {
	if in == nil {
		return nil
	}
	out := new(AlertTier)
	in.DeepCopyInto(out)
	return out
}

func (in *SLOStatus) DeepCopyInto(out *SLOStatus) {
	*out = *in
	if in.Conditions != nil {
		out.Conditions = make([]v1.Condition, len(in.Conditions))
		for i := range in.Conditions {
			in.Conditions[i].DeepCopyInto(&out.Conditions[i])
		}
	}
	if in.GeneratedRules != nil {
		out.GeneratedRules = make([]string, len(in.GeneratedRules))
		copy(out.GeneratedRules, in.GeneratedRules)
	}
	if in.LastReconcileAt != nil {
		out.LastReconcileAt = in.LastReconcileAt.DeepCopy()
	}
}

func (in *SLOStatus) DeepCopy() *SLOStatus {
	if in == nil {
		return nil
	}
	out := new(SLOStatus)
	in.DeepCopyInto(out)
	return out
}

func (in *SLO) DeepCopyInto(out *SLO) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

func (in *SLO) DeepCopy() *SLO {
	if in == nil {
		return nil
	}
	out := new(SLO)
	in.DeepCopyInto(out)
	return out
}

func (in *SLO) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *SLOList) DeepCopyInto(out *SLOList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		out.Items = make([]SLO, len(in.Items))
		for i := range in.Items {
			in.Items[i].DeepCopyInto(&out.Items[i])
		}
	}
}

func (in *SLOList) DeepCopy() *SLOList {
	if in == nil {
		return nil
	}
	out := new(SLOList)
	in.DeepCopyInto(out)
	return out
}

func (in *SLOList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}
